version: '3'
services:
  library:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      PORT: 8080
    networks:
      - backend

  postgres:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  database-data:

networks:
  backend: